name: skin_lesion_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pandas
  - opencv
  - matplotlib
  - pip
  - pip:
    - pathlib